[build]
target = "host/index.html"

[watch]
watch = [
    "app/src",
    "app/Cargo.toml",
    "host/src",
    "host/index.html",
    "host/worker.js",
    "host/Cargo.toml",
    "Cargo.toml",
]
ignore = ["target", "dist", ".git"]

[serve]
headers = { "Cache-Control" = "no-cache" }
